# Generated by Django 4.2.11 on 2024-04-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(blank=True, max_length=30, null=True)),
                ('entity_type', models.CharField(blank=True, choices=[('Big Entity', 'Big Entity'), ('Small Entity', 'Small Entity')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('Corporate', 'Corporate/Company'), ('Individual', 'Individual'), ('School', 'School'), ('Government', 'Government')], max_length=20, null=True)),
                ('client_name', models.CharField(max_length=200)),
                ('unit_description', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country_name', models.CharField(blank=True, max_length=30, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=60, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=30)),
                ('landline', models.CharField(blank=True, max_length=100)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('date_entered', models.DateField(blank=True, null=True)),
                ('client_type', models.CharField(blank=True, max_length=1, null=True)),
                ('account_officer', models.CharField(blank=True, max_length=50, null=True)),
                ('account_person', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Dormant', 'Dormant'), ('Delinquent', ' Delinquent')], default='Active', max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('entered_by', models.CharField(blank=True, max_length=15, null=True)),
                ('referredby', models.CharField(blank=True, max_length=150)),
                ('billing_to', models.CharField(blank=True, max_length=100)),
                ('billing_address', models.CharField(blank=True, max_length=200)),
                ('billing_attention', models.CharField(blank=True, max_length=60)),
                ('position', models.CharField(blank=True, max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updatedby', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
